'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Discussion_Forum

Partial Public Class AdminAuditLogsPage

    Protected WithEvents txtSearch As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents ddlAction As Global.System.Web.UI.WebControls.DropDownList
    Protected WithEvents btnFilter As Global.System.Web.UI.WebControls.Button
    Protected WithEvents btnClear As Global.System.Web.UI.WebControls.Button
    Protected WithEvents lblLogCount As Global.System.Web.UI.WebControls.Label
    Protected WithEvents rptLogs As Global.System.Web.UI.WebControls.Repeater
    Protected WithEvents pnlNoLogs As Global.System.Web.UI.WebControls.Panel
End Class

End Namespace
