'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Discussion_Forum

Partial Public Class AdminDashboardPage

    Protected WithEvents lblTotalUsers As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblActiveUsers As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblTotalThreads As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblTotalReplies As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblActiveThreads As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblWeeklyThreads As Global.System.Web.UI.WebControls.Label
    Protected WithEvents rptTopContributors As Global.System.Web.UI.WebControls.Repeater
    Protected WithEvents rptRecentLogs As Global.System.Web.UI.WebControls.Repeater
End Class

End Namespace
