'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Discussion_Forum

Partial Public Class AdminUsersPage

    Protected WithEvents pnlSuccess As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lblSuccess As Global.System.Web.UI.WebControls.Label
    Protected WithEvents txtSearch As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents lblUserCount As Global.System.Web.UI.WebControls.Label
    Protected WithEvents rptUsers As Global.System.Web.UI.WebControls.Repeater
End Class

End Namespace
