'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _Default

    Protected WithEvents txtSearch As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents rptThreads As Global.System.Web.UI.WebControls.Repeater
    Protected WithEvents pnlNoThreads As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents pnlPagination As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lblTotalThreads As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblTotalReplies As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblTotalMembers As Global.System.Web.UI.WebControls.Label
    Protected WithEvents rptContributors As Global.System.Web.UI.WebControls.Repeater
End Class
