'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ErrorPage

    Protected WithEvents lblErrorCode As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblErrorTitle As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblErrorMessage As Global.System.Web.UI.WebControls.Label
End Class
