'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class LoginPage

    Protected WithEvents pnlError As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label
    Protected WithEvents pnlSuccess As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lblSuccess As Global.System.Web.UI.WebControls.Label
    Protected WithEvents txtEmail As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtPassword As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents btnLogin As Global.System.Web.UI.WebControls.Button
End Class
