'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class NewThreadPage

    Protected WithEvents pnlError As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label
    Protected WithEvents txtTitle As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtBody As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents btnSubmit As Global.System.Web.UI.WebControls.Button
End Class
