'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ProfilePage

    Protected WithEvents divProfileAvatar As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    Protected WithEvents lblDisplayName As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblUsername As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblRoleBadge As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblBio As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblJoined As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblThreadCount As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblReplyCount As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblLikesReceived As Global.System.Web.UI.WebControls.Label
    Protected WithEvents pnlEditBtn As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents btnToggleEdit As Global.System.Web.UI.WebControls.Button
    Protected WithEvents pnlEditForm As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents pnlEditError As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lblEditError As Global.System.Web.UI.WebControls.Label
    Protected WithEvents pnlEditSuccess As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lblEditSuccess As Global.System.Web.UI.WebControls.Label
    Protected WithEvents txtEditDisplayName As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtEditBio As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents btnSaveProfile As Global.System.Web.UI.WebControls.Button
    Protected WithEvents btnCancelEdit As Global.System.Web.UI.WebControls.Button
    Protected WithEvents rptUserThreads As Global.System.Web.UI.WebControls.Repeater
    Protected WithEvents pnlNoThreads As Global.System.Web.UI.WebControls.Panel
End Class
