'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class RegisterPage

    Protected WithEvents pnlError As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label
    Protected WithEvents txtUsername As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtDisplayName As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtEmail As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtPassword As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtConfirmPassword As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents btnRegister As Global.System.Web.UI.WebControls.Button
End Class
