'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SiteMaster

    Protected WithEvents pnlGuest As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents pnlUser As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents pnlAdmin As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lblUserDisplay As Global.System.Web.UI.WebControls.Label
    Protected WithEvents btnLogout As Global.System.Web.UI.WebControls.LinkButton
    Protected WithEvents MainContent As Global.System.Web.UI.WebControls.ContentPlaceHolder
End Class
