'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ThreadViewPage

    Protected WithEvents lblTitle As Global.System.Web.UI.WebControls.Label
    Protected WithEvents divAvatar As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    Protected WithEvents lblAuthor As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblRoleBadge As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblTime As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblStatusBadge As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblBody As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblViews As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblReplyCount As Global.System.Web.UI.WebControls.Label
    Protected WithEvents pnlModActions As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents btnClose As Global.System.Web.UI.WebControls.Button
    Protected WithEvents btnPin As Global.System.Web.UI.WebControls.Button
    Protected WithEvents btnArchive As Global.System.Web.UI.WebControls.Button
    Protected WithEvents btnReopen As Global.System.Web.UI.WebControls.Button
    Protected WithEvents btnDelete As Global.System.Web.UI.WebControls.Button
    Protected WithEvents rptReplies As Global.System.Web.UI.WebControls.Repeater
    Protected WithEvents pnlNoReplies As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents pnlReplyForm As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents pnlReplyError As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lblReplyError As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblMyInitials As Global.System.Web.UI.WebControls.Label
    Protected WithEvents txtReply As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents btnReply As Global.System.Web.UI.WebControls.Button
    Protected WithEvents pnlLoginPrompt As Global.System.Web.UI.WebControls.Panel
End Class
